version: "3.2"

services:
  backend:
    image: node:10
    volumes:
      - ./backend:/server
    command: sh -c 'cd /server && yarn && yarn test'
  db:
    ports:
      - 3306:3306
    volumes:
      - ./volumes-test/database:/var/lib/mysql
