version: "3.2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_FILES_PATH:-./nginx-data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx-data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./nginx-data}/certs:/etc/nginx/certs:ro
      - ./nginx-proxy/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${NGINX_FILES_PATH:-./nginx-data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./nginx-data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./nginx-data}/certs:/etc/nginx/certs:rw
  nginx:
    image: nginx:alpine
    restart: always
    environment:
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${NGINX_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/sites-enabled/server.conf:/etc/nginx/sites-enabled/server.conf
      - ./public:/tmp/public
  backend:
    build: ./backend
    image: iceprojectbackend
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${BACKEND_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${BACKEND_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
